import { Router, Request, Response } from 'express';
import { prisma } from '../lib/db';

const router = Router();

// POST /api/pmta/generate/:nodeId
router.post('/generate/:nodeId', async (req: Request, res: Response) => {
  try {
    const node = await prisma.node.findUniqueOrThrow({
      where: { id: req.params.nodeId },
      include: { ips: true },
    });

    const domain = (req.query.domain as string) || '';
    let dkimBlock = '';

    if (domain) {
      const sendingDomain = await prisma.sendingDomain.findUnique({ where: { domain } });
      if (sendingDomain) {
        // Strip PEM headers for PMTA
        const privKeyB64 = sendingDomain.dkimPrivateKey
          .replace(/-----BEGIN.*?-----/g, '')
          .replace(/-----END.*?-----/g, '')
          .replace(/\n/g, '');
        dkimBlock = `
<domain-key bounce-key>
  domain ${domain}
  selector ${sendingDomain.dkimSelector}
  type rsa
  private-key <key>
${privKeyB64}
  </key>
</domain-key>`;
      }
    }

    const rateLimits = await prisma.rateLimit.findMany();
    const rlMap = Object.fromEntries(rateLimits.map(r => [r.provider, r]));

    // Build virtual-mta blocks per IP
    const vmtaBlocks = node.ips.map(ip => {
      const provider = ip.provider || 'default';
      const rl = rlMap[provider] || rlMap['default'] || { maxSmtpOut: 10, maxMsgRatePerHour: 500, connectTimeout: 30 };
      return `
<virtual-mta ${provider}-${ip.ip.replace(/\./g, '-')}>
  smtp-source-ip ${ip.ip}
  max-smtp-out ${rl.maxSmtpOut}
  max-connect-rate ${rl.maxMsgRatePerHour}/hour
  smtp-timeout ${rl.connectTimeout}
</virtual-mta>`;
    }).join('\n');

    // Build domain-specific routing
    const domainRouting = Object.entries(rlMap).filter(([p]) => p !== 'default').map(([p, rl]) => `
<domain ${p}>
  max-smtp-out ${rl.maxSmtpOut}
  max-msg-rate ${rl.maxMsgRatePerHour}/hour
</domain>`).join('\n');

    const config = `<?xml version="1.0"?>
<!-- PowerMTA Configuration for ${node.hostname} (${node.ip}) -->
<!-- Generated by Bounce-CLN on ${new Date().toISOString()} -->

<config>

<!-- Logging -->
<acct-file /var/log/pmta/accounting.csv>
  records b, rb, rp, rs, bd
  move-interval 1h
  max-size 10m
</acct-file>

<!-- EHLO/HELO hostname -->
smtp-client-host ${node.hostname}

<!-- DKIM Signing ${dkimBlock ? '' : '(no domain configured)'} -->
${dkimBlock}

<!-- Virtual MTAs per IP -->
${vmtaBlocks}

<!-- Per-domain rate limits -->
${domainRouting}

<!-- Default virtual MTA -->
<virtual-mta default>
  smtp-source-ip ${node.ips[0]?.ip || node.ip}
  max-smtp-out 10
  max-connect-rate 500/hour
</virtual-mta>

<!-- Bounce handling -->
<virtual-mta-pool all-ips>
${node.ips.map(ip => `  virtual-mta ${(ip.provider || 'default')}-${ip.ip.replace(/\./g, '-')}`).join('\n')}
</virtual-mta-pool>

</config>`;

    res.json({ config });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// POST /api/pmta/deploy/:nodeId — deploy config via SSH
router.post('/deploy/:nodeId', async (req: Request, res: Response) => {
  try {
    const node = await prisma.node.findUniqueOrThrow({ where: { id: req.params.nodeId } });
    const { config } = req.body;
    if (!config) { res.status(400).json({ error: 'config is required' }); return; }

    const { executeSSH } = await import('../lib/ssh');
    const fs = await import('fs/promises');
    const path = await import('path');
    const os = await import('os');

    const tmpPath = path.join(os.tmpdir(), `pmta-${node.id}.xml`);
    await fs.writeFile(tmpPath, config, 'utf8');

    const { uploadFile } = await import('../lib/ssh');
    await uploadFile(
      { host: node.ip, port: node.sshPort, username: node.sshUser },
      tmpPath,
      '/etc/pmta/config'
    );

    await executeSSH(
      { host: node.ip, port: node.sshPort, username: node.sshUser },
      ['pmta reload || true']
    );

    await fs.unlink(tmpPath).catch(() => {});
    await prisma.node.update({ where: { id: node.id }, data: { pmtaConfigured: true } });

    res.json({ ok: true, message: 'Config deployed and PowerMTA reloaded' });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

export default router;
